
#This is autogenerated, don't modify it you'll lost your mods...
url = "http://localhost"
port = 10000

import requests
import json

def send_http(cmd, data):
    _r = {}
    _r["sended"] = False

    full_url = f"{url}:{port}/{cmd}"
    try:
        response = requests.post(full_url, json=data)
        response.raise_for_status()  # Raise error for bad HTTP status codes
        _r["sended"] = True
        data = {}
        try : 
            data = json.loads(response.text)
        except : 
            _r["success"] = False
            _r["error"] = "Can't parse the response as a JSON"
            _r["response"] = response.text
            _r["status"] = response.status_code

        if not data : 
            return _r

        for k in data : 
            _r[k] = data[k]
        
    except requests.RequestException as e:
        _r["error"] = str(e)
    return _r


listeners = []
# id correspond to the id of the object sending the event.
def add_listener(event_type, callback, id=""):
    global listeners
    l = {"type" : event_type, "callback" : callback, "id" : id}
    listeners.append(l)

headers = {
    "Accept": "text/event-stream",
    "Cache-Control": "no-cache",
    # IMPORTANT: disable compression; decompressors buffer and delay lines
    "Accept-Encoding": "identity",
}

#you can call ths function at the end of your program to react to the GUI events
#The listeners callbacks will be called on the tread where "listen" is called
#It's a blocking function
def listen() : 
    full_url = f"{url}:{port}/sse"
    with requests.get(full_url, stream=True, headers=headers) as resp:
        resp.raise_for_status()
        buffer = []
        event_type = "message"
        event_id = None

        for raw_line in resp.iter_lines(chunk_size=1, decode_unicode=True, delimiter="\n"):
            if raw_line is None:   # keep-alive
                continue
            line = raw_line.strip()
            if line.startswith("data:") : 
                data = json.loads(line[5:])
                for l in listeners :
                    if data["type"] == l["type"] : 
                        if l["id"] == "" or l["id"] == data["id"] : 
                            l["callback"](data)

#The listeners callbacks will never be called on the mainthread.
def listen_async() : 
    import threading
    threading.Thread(target=listen).start()

#Example for a listener of the "cancelled" event on any windows/objects (add the id parameter if you want to filter them)
#   add_listener("cancelled", lambda data : print ("Test data received : " + str(data)))

#listen on the main thread : 
#   listen()

#listen on a separate thread async :
#   listen_async()
