#!/usr/bin/python3
import os
import shutil
import site

current = os.path.dirname(__file__)
packagesDir = site.getsitepackages()[0]

print ("installing py-utils from fxos to " + packagesDir + " ... ")

if os.path.exists(packagesDir + "/ml"): 
    print ("old version of py-utils found. Removing it.")
    shutil.rmtree(packagesDir + "/ml")

shutil.copytree(current, packagesDir + "/ml")
print ("py-utils from fxos installed.")
