#!/usr/bin/python3
import os
import shutil
import site

installDir = site.getsitepackages()[0]+ "/ml"

if not os.path.exists(installDir) : 
    print ("py-utils not installed.")
else : 
    shutil.rmtree(installDir)
    print ("py-utils uninstalled.")
